### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by rekire** [bkbilly/mqtt_fingerprint_pi#1]
Your repo looks quiet helpful, but I'm not sure how I need to connect the finger print sensor with my raspberry pi. Can you be so kind to update your readme file to explain that?

**Comment by bkbilly** [comment]
The R503 fingerprint sensor has 6 wires but only 4 are used and they should be connected like so:
|     R503 Sensor      |     Raspberry PI     |
| -------------------- | ------------------------- |
| RED (Power 3V)       | [3.3V](https://pinout.xyz/pinout/3v3_power)  |
| BLACK (GND)          | [Ground](https://pinout.xyz/pinout/ground)  |
| YELLOW (TXD)         | [UART RX](https://pinout.xyz/pinout/pin10_gpio15)  |
| GREEN (RXD)          | [UART TX](https://pinout.xyz/pinout/pin8_gpio14)  |
| BLUE (Wakeup)        | Not connected  |
| WHITE (3.3VT)        | Not connected  |

**Comment by bkbilly** [comment]
I've also updated the README. Hope it helps!

**Comment by rekire** [comment]
Yes it does! Thank you. I'll check if I can make it running with that information.

Even if unrelated is there any reason why did not connect the blue wakeup pin? Out of my understanding it could be used to trigger a notification or similar.

**Comment by bkbilly** [comment]
It wasn't needed for my app to work because once it recognizes a finger, it will instantly send the authorized/unauthorized command. Also I already had 4 wires going to my sensor and I couldn't add more.

One thing I don't really understand is what the usage of the white wire that some people connect it with the 3.3v. I haven't connected it and it works perfectly...
